# Generated by Django 6.0.4 on 2026-04-09 15:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(help_text='Retailer, Plumber, Builder, Dealer, etc.', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiscountGroup',
            fields=[
                ('disc_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., Retailers Gold', max_length=100, unique=True)),
                ('base_percent', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('inquiry_type', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Inquiries',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('product_color', models.CharField(blank=True, max_length=50, null=True)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('current_stock', models.IntegerField(default=0)),
                ('capacity', models.CharField(blank=True, max_length=50, null=True)),
                ('warranty', models.CharField(blank=True, max_length=50, null=True)),
                ('max_head', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('reward_id', models.AutoField(primary_key=True, serialize=False)),
                ('reward_type', models.CharField(max_length=100)),
                ('reward_points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('Conversation_Id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='open', max_length=20)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConversationParticipant',
            fields=[
                ('Participant_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_type', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='base.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_participations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('gst_id', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_address', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL)),
                ('customer_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.customertype')),
                ('reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.reward')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('Message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message_text', models.TextField()),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('order_request', 'Order Request'), ('order_received', 'Order Received'), ('system', 'System'), ('forwarded', 'Forwarded'), ('Order Accepted', 'order_accepted'), ('Rejected', 'Rejected'), ('return_request', 'Return Request'), ('return_approved', 'Return Approved'), ('return_rejected', 'Return Rejected'), ('payment_recorded', 'Payment Recorded')], default='text', max_length=50)),
                ('sender_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('Conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='base.conversation')),
                ('Sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('Order_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Order_date', models.DateTimeField(auto_now_add=True)),
                ('Total_Amount', models.FloatField()),
                ('actual_qty_packed', models.IntegerField(blank=True, null=True)),
                ('Status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('full', 'Full Payment'), ('partial', 'Partial Payment'), ('due', 'Due / Unpaid')], default='due', max_length=20)),
                ('amount_paid', models.FloatField(default=0.0)),
                ('percentage_paid', models.FloatField(default=0.0)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.customer')),
                ('Employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderAction',
            fields=[
                ('action_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=50)),
                ('reason', models.TextField(blank=True, null=True)),
                ('expected_delivery', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('performed_by_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_actions', to='base.conversation')),
                ('performed_by', models.ForeignKey(db_column='performed_by_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='base.orders')),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='Order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.orders'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('mode', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('neft', 'NEFT / Bank Transfer'), ('upi', 'UPI / Online'), ('other', 'Other')], max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='base.orders')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pending_registration', to='base.customer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pending_registration', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('Item_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Qty', models.IntegerField()),
                ('Actual_Qty', models.IntegerField(blank=True, null=True)),
                ('MRP', models.FloatField()),
                ('Selling_Price', models.FloatField()),
                ('Line_Total', models.FloatField()),
                ('Discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.discountgroup')),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='base.orders')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.productbrand'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.productcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='base.productmaterial'),
        ),
        migrations.CreateModel(
            name='ProductPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=100)),
                ('units_per_package', models.PositiveIntegerField()),
                ('sellable', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='base.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='base.productcategory')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.productsubcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='base.productunit'),
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('Return_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Return_Qty', models.IntegerField()),
                ('Return_reason', models.CharField(max_length=255)),
                ('Return_date', models.DateTimeField(auto_now_add=True)),
                ('Note_text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('Conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='base.conversation')),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='base.orders')),
                ('Order_Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_entries', to='base.orderitems')),
                ('Processed_By', models.ForeignKey(blank=True, db_column='Processed_By', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processed_returns', to=settings.AUTH_USER_MODEL)),
                ('Requested_By', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_requests', to='base.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_updated', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_updates', to='base.orders')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product')),
                ('return_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_updates', to='base.return')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('device_fingerprint', models.CharField(db_index=True, max_length=500)),
                ('logged_in_at', models.DateTimeField(blank=True, null=True)),
                ('logged_out_at', models.DateTimeField(blank=True, null=True)),
                ('hashed_user_id', models.CharField(blank=True, max_length=64, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('order_alerts', models.BooleanField(default=True)),
                ('marketing_emails', models.BooleanField(default=False)),
                ('customer_messages', models.BooleanField(default=True)),
                ('system_notifications', models.BooleanField(default=True)),
                ('low_stock_alerts', models.BooleanField(default=True)),
                ('alert_sound', models.BooleanField(default=True)),
                ('vibration', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='high', max_length=10)),
                ('two_factor', models.BooleanField(default=False)),
                ('session_timeout', models.BooleanField(default=True)),
                ('dark_mode', models.BooleanField(default=False)),
                ('compact_view', models.BooleanField(default=False)),
                ('language', models.CharField(default='en', max_length=10)),
                ('number_format', models.CharField(default='en-IN', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerDiscountMap',
            fields=[
                ('map_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_discount_maps', to='base.customertype')),
                ('discount_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_maps', to='base.discountgroup')),
            ],
            options={
                'unique_together': {('customer_type', 'discount_group')},
            },
        ),
        migrations.CreateModel(
            name='CustomerDiscountGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.customer')),
                ('discount_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.discountgroup')),
            ],
            options={
                'unique_together': {('customer', 'discount_group')},
            },
        ),
        migrations.CreateModel(
            name='DiscountGroupBrandMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_links', to='base.discountgroup')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.productbrand')),
            ],
            options={
                'unique_together': {('group', 'brand')},
            },
        ),
        migrations.CreateModel(
            name='DiscountGroupCategoryMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_links', to='base.discountgroup')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.productcategory')),
            ],
            options={
                'unique_together': {('group', 'category')},
            },
        ),
        migrations.CreateModel(
            name='DiscountGroupSubCategoryMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_links', to='base.discountgroup')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.productsubcategory')),
            ],
            options={
                'unique_together': {('group', 'sub_category')},
            },
        ),
        migrations.CreateModel(
            name='BrandSubCategoryMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_mappings', to='base.productbrand')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_mappings', to='base.productsubcategory')),
            ],
            options={
                'unique_together': {('brand', 'sub_category')},
            },
        ),
        migrations.CreateModel(
            name='UserGroupDiscountProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_discounts', to='base.customertype')),
                ('discount_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_types', to='base.discountgroup')),
            ],
            options={
                'verbose_name': 'Group Discount Mapping',
                'unique_together': {('customer_type', 'discount_group')},
            },
        ),
    ]
