const ProductDescription = [
    {
        id: 1, 
        product_name: 'Bib Cock', 
        product_code: '', 
        current_stock: '150', 
        units: 'Pcs', 
        size: '', 
        material: 'UPVC',
        Category_Id:1,
        Sub_Category:1,
        Brand_Id:6,
        product_description: "Durable UPVC wall tap for cold water supply.", 
        price: 41.5, 
        product_color: 'White',
        capacity: "", 
        max_head: 0, 
        warranty: ""
    },
    {
        id: 2, 
        product_name: 'Nozzal Cock', 
        product_code: '', 
        current_stock: '250', 
        units: 'Pcs', 
        size: '', 
        material: 'UPVC',
        Category_Id:1,
        Sub_Category:1,
        Brand_Id:6,
        product_description: "UPVC tap with nozzle for hose pipe connection.", 
        price: 43.5, 
        product_color: 'White',
        capacity: "", 
        max_head: 0, 
        warranty: ""
    },
    {
        id: 3, 
        product_name: 'Long Nose', 
        product_code: '', 
        current_stock: '150', 
        units: 'Pcs', 
        size: '',
        material: 'UPVC',
        Category_Id:1,
        Sub_Category:1,
        Brand_Id:6,
        product_description: "Extended body bib cock for extra reach.", 
        price: 52.5, 
        product_color: 'White',
        capacity: "", 
        max_head: 0, 
        warranty: ""
    },
    {
        id: 4, 
        product_name: 'Piller Cock', 
        product_code: '', 
        current_stock: '200', 
        units: 'Pcs', 
        size: '', 
        material: 'UPVC',
        Category_Id:1,
        Sub_Category:1,
        Brand_Id:6, 
        product_description: "Washbasin mounted vertical tap.", 
        price: 52.5, 
        product_color: 'White',
        capacity: "", 
        max_head: 0, 
        warranty: ""
    },
    {
        id: 5, 
        product_name: 'Head Shower', 
        product_code: '', 
        current_stock: '200', 
        units: 'Pcs', 
        size: '4*4', 
        material: 'Stainless Steel',
        Category_Id:1,
        Sub_Category:2,
        Brand_Id:5,  
        product_description: "Square rain shower head with chrome finish.", 
        price: 150, 
        product_color: 'Silver',
        capacity: "", 
        max_head: 0, 
        warranty: ""
    },
    {
        id: 6, 
        product_name: 'Grohe HF 01', 
        product_code: '', 
        current_stock: '200', 
        units: 'Pcs', 
        size: '', 
        material: 'Stainless Steel',
        Category_Id:1,
        Sub_Category:3,
        Brand_Id:5, 
        product_description: "Premium health faucet with trigger control.", 
        price: 240, 
        product_color: 'Silver',
        capacity: "", 
        max_head: 0, 
        warranty: ""
    },
    {
        id: 7, 
        product_name: 'I20 HF 14', 
        product_code: '', 
        current_stock: '200', 
        units: 'Pcs', 
        size: '', 
        material: 'Stainless Steel',
        Category_Id:1,
        Sub_Category:3,
        Brand_Id:5,  
        product_description: "High-quality health faucet / jet spray.", 
        price: 240, 
        product_color: 'Silver',
        capacity: "", 
        max_head: 0, 
        warranty: ""
    },
    {
        id: 8, 
        product_name: 'Concelo Cistern', 
        product_code: '14006', 
        current_stock: '200', 
        units: 'Pcs', 
        size: '', 
        material: 'UPVC',
        Category_Id:2,
        Sub_Category:5,
        Brand_Id:4, 
        product_description: "Single flush concealed cistern.", 
        price: 3650, 
        product_color: 'white',
        capacity: "", 
        max_head: 0, 
        warranty: ""
    },
    {
        id: 9, 
        product_name: 'Concelo Cistern', 
        product_code: '14007', 
        current_stock: '200', 
        units: 'Pcs', 
        size: '', 
        material: 'UPVC',
        Category_Id:2,
        Sub_Category:5,
        Brand_Id:4,  
        product_description: "Dual flush concealed cistern.", 
        price: 5500, 
        product_color: 'Silver',
        capacity: "", 
        max_head: 0, 
        warranty: ""
    },
    {
        id: 10, 
        product_name: 'Concealed Cistern', 
        product_code: '10014006', 
        current_stock: '200', 
        units: 'Pcs', 
        size: '', 
        material: 'UPVC',
        Category_Id:2,
        Sub_Category:5,
        Brand_Id:4,  
        product_description: "Premium wall-mounted flushing system.", 
        price: 7500, 
        product_color: 'white',
        capacity: "", 
        max_head: 0, 
        warranty: ""
    },
    {
        id: 11, 
        product_name: 'Pipe 4.5 KGS', 
        current_stock: '200', 
        units: 'Pcs', 
        size: '2 inches', 
        material: 'UPVC',
        Category_Id:3,
        Sub_Category:10,
        Brand_Id:1,  
        product_description: "Heavy-duty UPVC plumbing pipe.", 
        price: 241, 
        product_color: 'white',
        capacity: "", 
        max_head: 0, 
        warranty: ""
    },
    {
        id: 12, 
        product_name: 'Pipe 4.5 KGS', 
        current_stock: '200', 
        units: 'Pcs', 
        size: '3 inches', 
        material: 'UPVC', 
        Category_Id:3,
        Sub_Category:10,
        Brand_Id:1, 
        product_description: "Heavy-duty UPVC plumbing pipe.", 
        price: 495, 
        product_color: 'white',
        capacity: "", 
        max_head: 0, 
        warranty: ""
    },
    {
        id: 13, 
        product_name: 'Pipe 4.5 KGS', 
        current_stock: '200', 
        units: 'Pcs', 
        size: '4 inches', 
        material: 'UPVC',
        Category_Id:3,
        Sub_Category:10,
        Brand_Id:1, 
        product_description: "Heavy-duty UPVC plumbing pipe.", 
        price: 720, 
        product_color: 'white',
        capacity: "", 
        max_head: 0, 
        warranty: ""
    },
    {
        id: 14, 
        product_name: 'Pipe 4.5 KGS', 
        current_stock: '200', 
        units: 'Pcs', 
        size: '6 inches', 
        material: 'UPVC',
        Category_Id:3,
        Sub_Category:10,
        Brand_Id:1,  
        product_description: "Heavy-duty UPVC plumbing pipe.", 
        price: 1295, 
        product_color: 'white',
        capacity: "", 
        max_head: 0, 
        warranty: ""
    },
    {
        id: 15, 
        product_name: 'Pipe Type A', 
        current_stock: '200', 
        units: 'Pcs', 
        size: '2 inches', 
        material: 'UPVC',
        Category_Id:3,
        Sub_Category:10,
        Brand_Id:1,
        product_description: "Standard Type A drainage pipe.", 
        price: 339, 
        product_color: 'white',
        capacity: "", 
        max_head: 0, 
        warranty: ""
    },
    {
        id: 16, 
        product_name: 'Pipe Type A', 
        current_stock: '200', 
        units: 'Pcs', 
        size: '3 inches', 
        material: 'UPVC',
        Category_Id:3,
        Sub_Category:10,
        Brand_Id:1,
        product_description: "Standard Type A drainage pipe.", 
        price: 657, 
        product_color: 'white',
        capacity: "", 
        max_head: 0, 
        warranty: ""
    },
    {
        id: 17, 
        product_name: 'Pipe Type A', 
        current_stock: '200', 
        units: 'Pcs', 
        size: '4 inches', 
        material: 'UPVC',
        Category_Id:3,
        Sub_Category:10,
        Brand_Id:1,
        product_description: "Standard Type A drainage pipe.", 
        price: 861, 
        product_color: 'white',
        capacity: "", 
        max_head: 0, 
        warranty: ""
    },
    {
        id: 18, 
        product_name: 'Pipe Type A', 
        current_stock: '200', 
        units: 'Pcs', 
        size: '6 inches', 
        material: 'UPVC', 
        Category_Id:3,
        Sub_Category:10,
        Brand_Id:1, 
        product_description: "Standard Type A drainage pipe.", 
        price: 1925, 
        product_color: 'white',
        capacity: "", 
        max_head: 0, 
        warranty: ""
    },
    {
        id: 19, 
        product_name: 'Elbow Prestige', 
        current_stock: '200', 
        units: 'Pcs', 
        size: '2 inches', 
        material: 'UPVC', 
        Category_Id:3,
        Sub_Category:12,
        Brand_Id:1, 
        product_description: "UPVC Pipe Fitting - Elbow.", 
        price: 14.92, 
        product_color: 'white',
        capacity: "", 
        max_head: 0, 
        warranty: "",
    },
    {
        id: 20, 
        product_name: 'Elbow Prestige', 
        current_stock: '200', 
        units: 'Pcs', 
        size: '3 inches', 
        material: 'UPVC',
        Category_Id:3,
        Sub_Category:12,
        Brand_Id:1, 
        product_description: "UPVC Pipe Fitting - Elbow.", 
        price: 28.1, 
        product_color: 'white',
        capacity: "", 
        max_head: 0, 
        warranty: "",
    },
    {
        id: 21, 
        product_name: 'Elbow Prestige', 
        current_stock: '200', 
        units: 'Pcs', 
        size: '4 inches', 
        material: 'UPVC',
        Category_Id:3,
        Sub_Category:12,
        Brand_Id:1,
        product_description: "UPVC Pipe Fitting - Elbow.", 
        price: 45.65, 
        product_color: 'white',
        capacity: "", 
        max_head: 0,
        warranty: "",
    },
    {
        id: 22, 
        product_name: 'Elbow Prestige', 
        current_stock: '200', 
        units: 'Pcs', 
        size: '6 inches', 
        material: 'UPVC',
        Category_Id:3,
        Sub_Category:12,
        Brand_Id:1,
        product_description: "UPVC Pipe Fitting - Elbow.", 
        price: 140.48, 
        product_color: 'white',
        capacity: "", 
        max_head: 0, 
        warranty: "",
    },
    {
        id: 23, 
        product_name: 'Tee Prestige', 
        current_stock: '200', 
        units: 'Pcs', 
        size: '2 inches', 
        material: 'UPVC',
        Category_Id:3,
        Sub_Category:13,
        Brand_Id:1,
        product_description: "UPVC Pipe Fitting - Tee.", 
        price: 18.9, 
        product_color: 'white',
        capacity: "", 
        max_head: 0, 
        warranty: "",
    },
    {
        id: 24, 
        product_name: 'Tee Prestige', 
        current_stock: '200', 
        units: 'Pcs', 
        size: '3 inches', 
        material: 'UPVC', 
        Category_Id:3,
        Sub_Category:13,
        Brand_Id:1,
        product_description: "UPVC Pipe Fitting - Tee.", 
        price: 34.68, 
        product_color: 'white',
        capacity: "", 
        max_head: 0, 
        warranty: "",
    },
    {
        id: 25, 
        product_name: 'Tee Prestige', 
        current_stock: '200', 
        units: 'Pcs', 
        size: '4 inches', 
        material: 'UPVC',
        Category_Id:3,
        Sub_Category:13,
        Brand_Id:1, 
        product_description: "UPVC Pipe Fitting - Tee.", 
        price: 58.82, 
        product_color: 'white',
        capacity: "", 
        max_head: 0, 
        warranty: "",
    },
    {
        id: 26, 
        product_name: 'Tee Prestige', 
        current_stock: '200', 
        units: 'Pcs', 
        size: '6 inches', 
        material: 'UPVC',
        Category_Id:3,
        Sub_Category:13,
        Brand_Id:1,
        product_description: "UPVC Pipe Fitting - Tee.", 
        price: 208.96, 
        product_color: 'white',
        capacity: "", 
        max_head: 0, 
        warranty: "",
    },
    {
        id: 27, 
        product_name: 'Mseal PhataPhat', 
        current_stock: '200', 
        units: 'Pcs', 
        size: '25 Gms', 
        material: 'Epoxy',
        Category_Id:3,
        Sub_Category:17,
        Brand_Id:7, 
        product_description: "Fast-setting multi-purpose epoxy putty.", 
        price: 10, 
        product_color: 'white',
        capacity: "", 
        max_head: 0, 
        warranty: "",
    },
    {
        id: 28, 
        product_name: 'Mseal PhataPhat Jar Pack', 
        current_stock: '200', 
        units: 'Jars', 
        size: '60 Gms', 
        material: 'Epoxy',
        Category_Id:3,
        Sub_Category:17,
        Brand_Id:7,
        product_description: "Epoxy putty in bulk jar packaging.", 
        price: 20, 
        product_color: 'white',
        capacity: "", 
        max_head: 0, 
        warranty: "",
    },
    {
        id: 29, 
        product_name: 'Mseal PV Seal Sol Cem', 
        current_stock: '200', 
        units: 'Jars', 
        size: '20 ML', 
        material: 'CPVC',
        Categry_Id:3,
        Sub_Category:18,
        Brand_Id:7,
        product_description: "Solvent cement for joining CPVC pipes.", 
        price: 40, 
        product_color: 'Yellow',
        capacity: "", 
        max_head: 0, 
        warranty: "",
    },
    {
        id: 30, 
        product_name: 'Mseal PV Seal Sol Cem Tube', 
        current_stock: '200', 
        units: 'Tubes', 
        size: '50 ML', 
        material: 'CPVC',
        Category_Id:3,
        Sub_Category:18,
        Brand_Id:7,
        product_description: "CPVC solvent cement in squeeze tube.", 
        price: 85, 
        product_color: 'white',
        capacity: "", 
        max_head: 0, 
        warranty: "",
    },
    {
        id: 31, 
        product_name: 'Revo Self Priming Pump H Plus', 
        current_stock: '200', 
        units: 'Pcs', 
        size: '', 
        material: 'Cast Iron',
        Category_Id:4,
        Sub_Category:19,
        Brand_Id:8,
        product_description: "Self-priming water pump for domestic use.", 
        price: 2570, 
        product_color: 'Blue',
        capacity: "0.5 HP", 
        max_head: 80, 
        warranty: "12 months",
    },
    {
        id: 32, 
        product_name: 'Revo Self Priming Pump F Plus', 
        current_stock: '200', 
        units: 'Pcs', 
        size: '', 
        material: 'Cast Iron',
        Category_Id:4,
        Sub_Category:19,
        Brand_Id:8,
        product_description: "Self-priming water pump for domestic use.", 
        price: 3540, 
        product_color: 'Blue',
        capacity: "1.0 HP", 
        max_head: 120, 
        warranty: "12 months",
    }
];

export default ProductDescription;