# ✅ FIXED urls.py
from . import views
from django.urls import path
from base.views import (
    ApproveRegistrationView,
    ConsumerRegistrationView,
    OverdueNotifyView,
    PendingRegistrationsView,
    RejectRegistrationView,
    SessionLoginView, 
    UserRegistrationView, 
    SessionLogoutView, 
    UserCustomerListView,
    GetUserInfoView, 
    GetActualUserRoleView,
    GetCSRFTokenView,
    DebugAuthView,
    ExtendSessionView,
    UserConsumerListView,
    ToggleUserStatusView,
    Get_Categories,
    Get_Sub_Categories_By_Categories,
    Get_Brands_By_Sub_Categories,
    Get_Form_Options,
    ProductRegistrationView,
    CustomerDiscListView,
    ProductListView,
    BulkDiscountView,
    CustomerDiscGrpAddition,
    manage_attribute,
    ReassignAttributeView,
    DiscountGroupSettingsView, 
    DiscountGroupDetailView,
    DiscountGroupAssociationsView,
    CreateOrderView,
    ConversationListView, 
    ConversationMessagesView,
    SendMessageView,
    UnreadCountView,
    AcceptOrderView,
    RejectOrderView,
    ForwardToOwnerView,
    CustomerOrderHistoryView,
    ConsumerListView,
    CustomerAcceptedOrdersView,
    ReturnOrderView,
    RecordPaymentView,
    PaymentHistoryView,
    DailyPaymentSummaryView,
    OrderStatusUpdateView,
    ActiveOrdersView,
    OrderReceivedView,
    ConsumerDueOrdersView,
    CustomerDueOrdersView,
    UserSettingsView,
    ChangePasswordView,
    OverduePaymentsView,
    InquirySubmissionView,
)


urlpatterns = [
    # Session-based authentication
    path('', SessionLoginView.as_view(), name='login'),
    path('register/', UserRegistrationView.as_view(), name='user_registration'),
    path('consumer/register/', ConsumerRegistrationView.as_view(), name='user_registration'),
    path('logout/', SessionLogoutView.as_view(), name='logout'),
    
    path('registrations/pending/',           PendingRegistrationsView.as_view()),
    path('registrations/<int:registration_id>/approve/', ApproveRegistrationView.as_view()),
    path('registrations/<int:registration_id>/reject/',  RejectRegistrationView.as_view()),

    # User management
    path("manage-attribute/", manage_attribute, name="manage-attribute"),
    path('reassign-attribute/', ReassignAttributeView.as_view()),
    path('users/customers/', UserCustomerListView.as_view(), name='customers_list'),
    path('users/customers-disc/', CustomerDiscListView.as_view(), name='customers_discount_list'),
    path('customer-type/<str:type_name>/bulk-discounts/', BulkDiscountView.as_view()),
    path('users/employee/consumers/', UserConsumerListView.as_view(), name='consumers_list'),
    path('users/toggle-status/', ToggleUserStatusView.as_view(), name='toggle_userStatus'),
    path('customers/<int:customer_id>/discount-groups/', CustomerDiscGrpAddition.as_view(), name='discount_grp_addition'),
    path('product/categories/', Get_Categories.as_view(), name='get_categories'),
    path('product/subcategories/', Get_Sub_Categories_By_Categories.as_view(), name='get_sub_categories'),
    path('product/brands-by-subcategory/', Get_Brands_By_Sub_Categories.as_view(), name='get_sub_categories'),
    path('product/form-options/', Get_Form_Options.as_view(), name='get_form_options'),
    # The <int:product_id> allows the URL to capture the number and pass it to your 'put' method
    path('product/register/', ProductRegistrationView.as_view(), name='product_register_view'),
    path('product/register/<int:product_id>/', ProductRegistrationView.as_view(), name='product_update_view'),
    path('product/', ProductListView.as_view(), name='product_list'),
    # Auth endpoints
    path('user-info/', GetUserInfoView.as_view(), name='user_info'),
    path('actual-user-role/', GetActualUserRoleView.as_view(), name='actual_user_role'),
    path('csrf-token/', GetCSRFTokenView.as_view(), name='csrf_token'),
    path('debug-auth/', DebugAuthView.as_view(), name='debug_auth'),
    path('extend-session/', ExtendSessionView.as_view(), name='extend_session'),

    path('discount-groups/',         DiscountGroupSettingsView.as_view()),
    path('discount-groups/<int:disc_id>/', DiscountGroupDetailView.as_view()),
    path('discount-groups/<int:disc_id>/associations/',   DiscountGroupAssociationsView.as_view()),

    path("orders/create/", CreateOrderView.as_view(), name="create-order"),
    path('messages/send/',  SendMessageView.as_view()),
    path('orders/<int:order_id>/accept/',  AcceptOrderView.as_view()),
    path('orders/<int:order_id>/reject/',  RejectOrderView.as_view()),
    path('orders/<int:order_id>/forward/', ForwardToOwnerView.as_view()),  # ✅ add this
    path('orders/<int:order_id>/return/', ReturnOrderView.as_view()),
    path('customers/accepted-orders/', CustomerAcceptedOrdersView.as_view()),
    path('customers/<int:customer_id>/accepted-orders/', CustomerAcceptedOrdersView.as_view()),  # ✅ for employee viewing customer
    path('messages/unread-count/', UnreadCountView.as_view()),
    path('messages/conversations/',          ConversationListView.as_view()),
    path('messages/<str:conversation_id>/',  ConversationMessagesView.as_view()),

    path('customers/<int:customer_id>/orders/', CustomerOrderHistoryView.as_view()),
    path('customers/consumers/', ConsumerListView.as_view()),

    path("orders/<int:order_id>/payment/",  RecordPaymentView.as_view(),   name="record-payment"),
    path("orders/<int:order_id>/payments/", PaymentHistoryView.as_view(),  name="payment-history"),
    path('orders/customer-due/', CustomerDueOrdersView.as_view()),
    path("payments/today/",                 DailyPaymentSummaryView.as_view(), name="payments-today"),
    path('orders/consumer-due/', ConsumerDueOrdersView.as_view()),

    path("orders/<int:order_id>/status/",   OrderStatusUpdateView.as_view()),
    path("orders/<int:order_id>/received/", OrderReceivedView.as_view()),
    path("orders/active/",                  ActiveOrdersView.as_view()),

    path('employee/settings/',         UserSettingsView.as_view()),
    path('employee/settings/update/',  UserSettingsView.as_view()),
    path('employee/change-password/',  ChangePasswordView.as_view()),

    path("payments/overdue/",        OverduePaymentsView.as_view()),
    path("payments/overdue/notify/", OverdueNotifyView.as_view()),

    path('report/<uuid:report_id>/', views.view_report, name='view_report'),
    path('home/interest/', InquirySubmissionView.as_view(), name='interest_calculator'),
]